spring:
  datasource:
    url: jdbc:mysql://183.237.21.252:13306/mysqltest
    username: mysqltest
    password: mysqltest
    hikari:
      idle-timeout: 300000
  jpa:
    properties:
      hibernate.enable_lazy_load_no_trans: true
#    hibernate:
#      ddl-auto: update

  data:
    mongodb:
      host: 183.237.21.252
      port: 27017
      database: Test_Mongodb
   
logging:
  level:
#    root: debug
    org.hibernate.SQL: debug