spring:
  datasource:
    url: jdbc:mysql://183.237.21.252:13306/mysqltest
    username: mysqltest
    password: mysqltest
  jpa:
    properties:
      hibernate.enable_lazy_load_no_trans: true
#    hibernate:
#      ddl-auto: update
      
logging:
  level:
#    root: debug
    org.hibernate.SQL: debug